name: Node.js CI

on: push

env:
  NPM_CONFIG_LOGLEVEL: error
  NPM_CONFIG_JOBS: max

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Cache node_modules/.cache
      uses: actions/cache@v1
      with:
        path: node_modules/.cache
        key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-run-id-${{ github.run_id }}
        restore-keys: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-
    - run: npm run eslint
    - run: npm run test -- --ci --coverage --maxWorkers 2
    - run: npx codecov
